### PR TITLE
Fix a typo and remove all redundant spaces

### PR DESCRIPTION
**Pull request by kngwyu**
Hi Jeremie, I'm too nervous and was not able to look over redundant spaces. Also, there is a typo in a comment.

### CODE REVIEW

**Comment by kngwyu** [comment]
Also, I propose to include `\usepackage{times}` for better appearance. If you agree, I'll make another PR.

**Comment by jiegillet** [comment]
Thank you, that's a good improvement. 
I usually use LaTeX with an editor that doesn't care about extra spaces, but I understand your struggle :)

What does `times` do?

**Comment by jiegillet** [comment]
[The package is now obsolete, replaced by the mathptmx package, which supports Times Roman text and (mostly) matching mathematics.](https://ctan.org/pkg/times?lang=en)

I think I would prefer using as little packages as possible for the template, and of course if people want to customize the look, they are free to do so. If it's OK with you I will merge the PR as it is now.

**Comment by kngwyu** [comment]
> I think I would prefer using as little packages as possible for the template, and of course if people want to customize the look, they are free to do so

Sounds reasonable 👍🏼

**Pull request merged**
